name: canvas-llm-integration
channels:
  - defaults
dependencies:
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates
  - expat=2.6.4
  - libffi=3.4.4
  - numexpr=2.10.1
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openssl=3.0.15
  - pandas=2.2.3
  - pip=24.2
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - pip:
      - annotated-types==0.7.0
      - anyio==4.8.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - attrs==24.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - git+https://github.com/lukekorthals/canvas-connector
      - canvasapi==3.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-mantine-components==0.15.1
      - dash-table==5.0.0
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - docopt==0.6.2
      - executing==2.1.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.5.0
      - ipykernel==6.29.5
      - ipython==8.12.3
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jiter==0.8.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - markdown-it-py==3.0.0
      - markdown-pdf==1.3.2
      - markupsafe==3.0.2
      - matplotlib-inline==0.1.7
      - matplotlib=3.10.0
      - mdurl==0.1.2
      - mistune==3.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - openai==1.59.4
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - prompt-toolkit==3.0.48
      - psutil==6.1.1
      - pure-eval==0.2.3
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pymupdf==1.24.2
      - pymupdfb==1.24.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.22.3
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tenacity==9.0.0
      - tinycss2==1.4.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - yarg==0.1.9
      - zipp==3.21.0
variables:
  CANVAS_API_URL: ENTER_YOUR_URL
  CANVAS_API_KEY: ENTER_YOUR_KEY
  CANVAS_USER_ID: ENTER_YOUR_ID
  OPENAI_API_KEY: ENTER_YOUR_KEY
  